image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - .sonar/cache

stages:
  - build
  - test
  - sonarqube-check

before_script:
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - echo "Building the project"

test:
  stage: test
  script:
    - echo "just a place holder"

variables:
  SONAR_PROJECT_KEY: "saxion.nl_hbo-ict_2.4-hbo-it-corp_09_AYjT3zZsny4zy3QfilO9" 
sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
